# Generated by Django 5.1.1 on 2024-09-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinaryCityApp', '0006_alter_contact_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(default='NON', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='BinaryCityApp.client'),
        ),
    ]
